# MySQL 数据库配置
db:
  host: 127.0.0.1               # 机器 IP 和端口
  username: zcar                # 用户名
  password: zcar1234            # 用户密码
  database: zcar                # miniblog 系统所用的数据库名
  max-idle-connections: 100     # 最大空闲连接数
  max-open-connections: 100     # 最大打开的连接数
  max-connection-life-time: 10s # 空闲连接最大存活时间
  log-level: 4                  # GORM log level, 1: silent, 2:error, 3:warn, 4:info